server:
  port: 8080

# mysql
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #MySQL????
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac_demo?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: P@ss1234
    hikari:
      minimum-idle: 5
      # ???????????????????600000??10?????
      idle-timeout: 180000
      # ?????????????????????10
      maximum-pool-size: 10
      # ???????????????????????????????,??????true
      auto-commit: true
      # ?????????
      pool-name: MyHikariCP
      # ?????????????????????????????0???????????????????1800000??30????
      max-lifetime: 1800000
      # ??????????????,???30????30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    #oracle????
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer????
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL????
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
  #    username: postgres
  #    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#?????????????ะก?mysql??oracle??sqlserver??postgresql??
renren:
  database: mysql
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
